on:
  release:
    types: [published]
name: Build Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json
      - name: detekt
        uses: natiginfo/action-detekt-all@1.19.0
        with:
          args: --config config/detekt.yml
      - name: Build with Gradle
        run: ./gradlew build
      - name: Releasing using Hub
        uses: galamdring/action-release-debugapk@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          APP_FOLDER: app
          RELEASE_TITLE: New Build
          VERSION_NAME: ${{ steps.get_tag_name.outputs.VERSION }}
          INCLUDE_DEBUG_FREE: Y
          INCLUDE_DEBUG_PAID: Y
          INCLUDE_RELEASE_FREE: Y
          INCLUDE_RELEASE_PAID: Y
